spring.application.name=backgammon
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/backgammon
#spring.datasource.username=root
#spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=1003685514851-03cjd27fuubbcglcsoeohrvauvkjhpgk.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://backgammon-production.up.railway.app/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver